######################################################################
##
## Filename: dynamics_tb.udo
## Created on: Tue Dec 01 12:15:35 PM Pacific Standard Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
